name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.aaaa }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci      
      - name: Build code
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'aaaa={}' >> $GITHUB_OUTPUT ';'  
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output Contents
        run: ls
      - name: Output Filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy code
        run: echo "Deploying..." 